### ISSUE TITLE
Spawn in wall

### ISSUE THREAD

**Issue by pearsons** [ceruleanlabs/Chicago-Game-Jam-2013#1] opened 2013-10-27 14:59 UTC
I've spawned in walls at the beginning of levels a few times (maybe held down as level was loading?). Also, if you stop burning in a gate it keeps you stuck there. Cool stuff

**Comment by pearsons** [comment] 2013-10-27 15:37
As in the game is cool stuff

**Comment by bergren2** [comment] 2013-10-28 22:19
Ah yes, we'll have to take a look at both those bugs. A short term fix would be to add a Reset button since those bugs can still occur even after we made some attempts to fix them.

**Comment by bergren2** [comment] 2016-07-03 21:19
Reset button already added and haven't been able to reproduce. Closing.

**Closed as completed by bergren2** 2016-07-03 21:19 UTC
Labels: bug
